const LABELS = {
  asignado: 'Asignado',
  notificado: 'Notificado',
  contactado: 'Contactado',
  en_tratamiento: 'En tratamiento',
  completado: 'Completado',
  cancelado: 'Cancelado',
  derivacion_pendiente: 'Derivación pendiente',
  derivado: 'Derivado',
  pendiente: 'Pendiente',
  aprobada: 'Aprobada',
  rechazada: 'Rechazada',
  admin: 'Administrador',
  coordinator: 'Coordinador',
  student: 'Estudiante',
  system: 'Sistema',
  active: 'Activa',
  inactive: 'Inactiva',
  suspended: 'Suspendida',
  asignacion: 'Asignación',
  estado: 'Cambio de estado',
  nota: 'Nota de seguimiento',
  caso_registrado: 'Caso registrado',
  derivacion_solicitada: 'Derivación solicitada',
  derivacion_aprobada: 'Derivación aprobada',
  derivacion_rechazada: 'Derivación rechazada',
  precalificacion_validada: 'Precalificación revisada',
  reasignacion_origen: 'Reasignación',
  paciente_desactivado: 'Paciente desactivado',
  datos_actualizados: 'Datos actualizados',
  snapshot_migracion: 'Estado al incorporar el historial',
  notificacion_enviada: 'Notificación enviada',
  notificacion_fallida: 'Notificación fallida',
};
export function displayLabel(value) {
  return LABELS[value] || String(value || '').replaceAll('_', ' ');
}
