module.exports = {
  async up(db) {
    const client = await db.connect();
    try {
      await client.query('BEGIN');
      await client.query(`
        ALTER TABLE asignaciones ALTER COLUMN estado TYPE VARCHAR(24);
        ALTER TABLE asignaciones DROP CONSTRAINT asignaciones_estado_check;
        ALTER TABLE asignaciones ADD CONSTRAINT asignaciones_estado_check CHECK (estado IN
          ('asignado','notificado','contactado','en_tratamiento','completado','cancelado','derivacion_pendiente','derivado'));
        DROP INDEX uq_asignacion_activa_paciente;
        CREATE UNIQUE INDEX uq_asignacion_activa_paciente ON asignaciones(id_paciente)
          WHERE estado IN ('asignado','notificado','contactado','en_tratamiento','derivacion_pendiente');

        CREATE TABLE derivaciones (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          id_paciente BIGINT NOT NULL REFERENCES pacientes(id),
          id_asignacion_origen BIGINT NOT NULL REFERENCES asignaciones(id),
          id_estudiante_origen BIGINT NOT NULL REFERENCES estudiantes_odontologia(id),
          estado_anterior VARCHAR(24) NOT NULL,
          propuesta JSONB NOT NULL,
          validacion JSONB,
          estado VARCHAR(12) NOT NULL DEFAULT 'pendiente' CHECK (estado IN ('pendiente','aprobada','rechazada')),
          id_solicitante BIGINT REFERENCES users(id),
          id_revisor BIGINT REFERENCES users(id),
          motivo_revision TEXT,
          id_asignacion_destino BIGINT REFERENCES asignaciones(id),
          fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
          fecha_revision TIMESTAMPTZ
        );
        CREATE UNIQUE INDEX uq_derivacion_pendiente ON derivaciones(id_asignacion_origen) WHERE estado='pendiente';
        CREATE UNIQUE INDEX uq_credito_derivacion ON derivaciones(id_paciente,id_estudiante_origen) WHERE estado='aprobada';
        CREATE INDEX idx_derivaciones_estado ON derivaciones(estado,fecha_creacion);
        ALTER TABLE pacientes ADD COLUMN precalificacion_validada JSONB;
        ALTER TABLE pacientes ADD COLUMN precalificacion_sugerida JSONB;
        ALTER TABLE pacientes ADD COLUMN derivacion_id BIGINT REFERENCES derivaciones(id);

        CREATE TABLE historial_paciente (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          id_paciente BIGINT NOT NULL REFERENCES pacientes(id),
          id_asignacion BIGINT REFERENCES asignaciones(id),
          id_usuario BIGINT REFERENCES users(id),
          responsable VARCHAR(150) NOT NULL,
          rol VARCHAR(20) NOT NULL,
          tipo VARCHAR(40) NOT NULL,
          estado_anterior VARCHAR(24),
          estado_nuevo VARCHAR(24),
          nota TEXT,
          datos JSONB NOT NULL DEFAULT '{}',
          fecha TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        );
        CREATE INDEX idx_historial_paciente ON historial_paciente(id_paciente,fecha,id);
        INSERT INTO historial_paciente(id_paciente,id_asignacion,responsable,rol,tipo,estado_nuevo,nota,datos)
          SELECT id_paciente,id,'Sistema','system','snapshot_migracion',estado,observaciones_estudiante,
                 jsonb_build_object('observaciones_sistema',observaciones_sistema,'fecha_asignacion',fecha_asignacion)
            FROM asignaciones;
        CREATE FUNCTION impedir_edicion_historial() RETURNS trigger LANGUAGE plpgsql AS $$
          BEGIN RAISE EXCEPTION 'El historial solo permite agregar eventos'; END;
        $$;
        CREATE TRIGGER historial_inmutable BEFORE UPDATE OR DELETE ON historial_paciente
          FOR EACH ROW EXECUTE FUNCTION impedir_edicion_historial();
        UPDATE estudiantes_odontologia e SET casos_activos=(SELECT COUNT(*) FROM asignaciones a
          WHERE a.id_estudiante=e.id AND a.estado IN ('asignado','notificado','contactado','en_tratamiento','derivacion_pendiente'));

        ALTER TABLE notificaciones_email DROP CONSTRAINT notificaciones_estado_check;
        ALTER TABLE notificaciones_email ADD CONSTRAINT notificaciones_estado_check
          CHECK (estado IN ('pendiente','enviando','enviado','fallido'));
        ALTER TABLE notificaciones_email ADD COLUMN claim_token UUID;
        ALTER TABLE notificaciones_email ADD COLUMN fecha_reclamo TIMESTAMPTZ;
        ALTER TABLE notificaciones_email ADD COLUMN primer_intento TIMESTAMPTZ;
        ALTER TABLE notificaciones_email ADD COLUMN proximo_intento TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP;
        ALTER TABLE notificaciones_email ADD COLUMN proveedor_id VARCHAR(100);
        ALTER TABLE notificaciones_email ADD COLUMN payload_envio JSONB;
        ALTER TABLE notificaciones_email ADD COLUMN envio_incierto BOOLEAN NOT NULL DEFAULT FALSE;
      `);
      await client.query('COMMIT');
    } catch (error) {
      await client.query('ROLLBACK');
      throw error;
    } finally {
      client.release();
    }
  },
};
