module.exports = {
  async up(db) {
    const client = await db.connect();
    try {
      await client.query('BEGIN');
      await client.query(`
        CREATE TABLE IF NOT EXISTS users (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          email VARCHAR(255) NOT NULL UNIQUE,
          password VARCHAR(255) NOT NULL,
          nombre_completo VARCHAR(150) NOT NULL,
          role VARCHAR(20) NOT NULL DEFAULT 'coordinator'
            CONSTRAINT users_role_check CHECK (role IN ('admin', 'coordinator', 'student')),
          permissions JSONB NOT NULL DEFAULT '[]'::jsonb,
          codigo_estudiante VARCHAR(20) UNIQUE,
          telefono VARCHAR(20),
          status VARCHAR(20) NOT NULL DEFAULT 'active'
            CONSTRAINT users_status_check CHECK (status IN ('active', 'inactive', 'suspended')),
          refresh_token_hash CHAR(64),
          last_login TIMESTAMPTZ,
          created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
          updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        );

        CREATE INDEX IF NOT EXISTS idx_users_role_status ON users (role, status);

        CREATE TABLE IF NOT EXISTS estudiantes_odontologia (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          codigo_estudiante VARCHAR(20) NOT NULL UNIQUE,
          nombre_completo VARCHAR(150) NOT NULL,
          año_carrera VARCHAR(3) NOT NULL
            CONSTRAINT estudiantes_año_check CHECK (año_carrera IN ('4to', '5to')),
          telefono VARCHAR(20),
          email VARCHAR(255) NOT NULL UNIQUE,
          universidad VARCHAR(150),
          ciudad VARCHAR(30) NOT NULL
            CONSTRAINT estudiantes_ciudad_check CHECK (ciudad IN ('Metropolitana', 'Valparaíso', 'Concepción')),
          casos_completados INTEGER NOT NULL DEFAULT 0 CHECK (casos_completados >= 0),
          casos_necesarios INTEGER NOT NULL DEFAULT 10 CHECK (casos_necesarios > 0),
          casos_activos INTEGER NOT NULL DEFAULT 0 CHECK (casos_activos >= 0),
          estado VARCHAR(10) NOT NULL DEFAULT 'activo'
            CONSTRAINT estudiantes_estado_check CHECK (estado IN ('activo', 'inactivo')),
          fecha_registro TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
          fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        );

        CREATE INDEX IF NOT EXISTS idx_estudiantes_estado_carga
          ON estudiantes_odontologia (estado, casos_activos, casos_necesarios);

        CREATE TABLE IF NOT EXISTS pacientes (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          nombre_completo VARCHAR(150) NOT NULL,
          edad SMALLINT NOT NULL CHECK (edad BETWEEN 1 AND 120),
          telefono VARCHAR(20) NOT NULL,
          email VARCHAR(255),
          ciudad VARCHAR(30) NOT NULL
            CONSTRAINT pacientes_ciudad_check CHECK (ciudad IN ('Metropolitana', 'Valparaíso', 'Concepción')),
          sintomas_seleccionados JSONB,
          respuestas_cuestionario JSONB,
          pre_categorizacion_ia JSONB,
          fecha_pre_categorizacion TIMESTAMPTZ,
          nivel_dolor SMALLINT NOT NULL DEFAULT 0 CHECK (nivel_dolor BETWEEN 0 AND 10),
          dias_disponibles JSONB,
          horario_preferencia VARCHAR(100),
          tipo_tratamiento_inferido VARCHAR(100),
          prioridad VARCHAR(10) NOT NULL DEFAULT 'Moderada'
            CONSTRAINT pacientes_prioridad_check CHECK (prioridad IN ('Baja', 'Moderada', 'Alta', 'Muy Alta')),
          consentimiento_datos BOOLEAN NOT NULL DEFAULT FALSE,
          fecha_consentimiento TIMESTAMPTZ,
          estado VARCHAR(12) NOT NULL DEFAULT 'pendiente'
            CONSTRAINT pacientes_estado_check CHECK (estado IN ('pendiente', 'asignado', 'completado', 'cancelado')),
          activo BOOLEAN NOT NULL DEFAULT TRUE,
          fecha_registro TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
          fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        );

        CREATE INDEX IF NOT EXISTS idx_pacientes_cola
          ON pacientes (activo, estado, prioridad, fecha_registro);
        CREATE INDEX IF NOT EXISTS idx_pacientes_especialidad
          ON pacientes (tipo_tratamiento_inferido);

        CREATE TABLE IF NOT EXISTS especialidades_estudiante (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          id_estudiante BIGINT NOT NULL REFERENCES estudiantes_odontologia(id) ON DELETE CASCADE,
          especialidad VARCHAR(100) NOT NULL,
          clinica VARCHAR(80) NOT NULL
            CONSTRAINT especialidades_clinica_check CHECK (clinica IN (
              'Clínica para el Niño y Adolescente',
              'Clínica Integral Adulto y Gerontología'
            )),
          dia_semana VARCHAR(10) NOT NULL
            CONSTRAINT especialidades_dia_check CHECK (dia_semana IN (
              'lunes', 'martes', 'miercoles', 'jueves', 'viernes', 'sabado'
            )),
          hora_inicio TIME NOT NULL,
          hora_fin TIME NOT NULL,
          capacidad_pacientes SMALLINT NOT NULL DEFAULT 1 CHECK (capacidad_pacientes > 0),
          activo BOOLEAN NOT NULL DEFAULT TRUE,
          fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
          fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
          CONSTRAINT especialidades_horas_check CHECK (hora_fin > hora_inicio),
          CONSTRAINT uq_especialidad_horario UNIQUE (
            id_estudiante, especialidad, dia_semana, hora_inicio, hora_fin
          )
        );

        CREATE INDEX IF NOT EXISTS idx_especialidades_match
          ON especialidades_estudiante (especialidad, clinica, activo);

        CREATE TABLE IF NOT EXISTS asignaciones (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          id_paciente BIGINT NOT NULL REFERENCES pacientes(id),
          id_estudiante BIGINT NOT NULL REFERENCES estudiantes_odontologia(id),
          id_especialidad_estudiante BIGINT REFERENCES especialidades_estudiante(id) ON DELETE SET NULL,
          fecha_asignacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
          fecha_cita DATE NOT NULL,
          estado VARCHAR(20) NOT NULL DEFAULT 'asignado'
            CONSTRAINT asignaciones_estado_check CHECK (estado IN (
              'asignado', 'notificado', 'contactado', 'en_tratamiento', 'completado', 'cancelado'
            )),
          especialidad_asignada VARCHAR(100) NOT NULL,
          dia_semana_asignado VARCHAR(20) NOT NULL,
          hora_inicio_asignada TIME NOT NULL,
          hora_fin_asignada TIME NOT NULL,
          score_compatibilidad NUMERIC(5,4) NOT NULL CHECK (score_compatibilidad BETWEEN 0 AND 1),
          factores_matching JSONB NOT NULL,
          observaciones_sistema TEXT,
          observaciones_estudiante TEXT,
          fecha_contacto TIMESTAMPTZ,
          fecha_inicio_tratamiento TIMESTAMPTZ,
          fecha_completado TIMESTAMPTZ,
          fecha_cancelacion TIMESTAMPTZ,
          motivo_cancelacion TEXT,
          fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
          CONSTRAINT asignaciones_horas_check CHECK (hora_fin_asignada > hora_inicio_asignada)
        );

        CREATE UNIQUE INDEX IF NOT EXISTS uq_asignacion_activa_paciente
          ON asignaciones (id_paciente)
          WHERE estado IN ('asignado', 'notificado', 'contactado', 'en_tratamiento');
        CREATE INDEX IF NOT EXISTS idx_asignaciones_estudiante_fecha
          ON asignaciones (id_estudiante, fecha_cita, hora_inicio_asignada, estado);
        CREATE INDEX IF NOT EXISTS idx_asignaciones_estado ON asignaciones (estado);

        CREATE TABLE IF NOT EXISTS notificaciones_email (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          id_asignacion BIGINT REFERENCES asignaciones(id),
          id_estudiante BIGINT REFERENCES estudiantes_odontologia(id) ON DELETE SET NULL,
          id_paciente BIGINT REFERENCES pacientes(id) ON DELETE SET NULL,
          email_destino VARCHAR(255) NOT NULL,
          tipo_notificacion VARCHAR(50) NOT NULL,
          asunto VARCHAR(200) NOT NULL,
          mensaje TEXT,
          estado VARCHAR(10) NOT NULL DEFAULT 'pendiente'
            CONSTRAINT notificaciones_estado_check CHECK (estado IN ('pendiente', 'enviado', 'fallido')),
          intentos_envio SMALLINT NOT NULL DEFAULT 0 CHECK (intentos_envio >= 0),
          error_envio TEXT,
          fecha_envio TIMESTAMPTZ,
          fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        );

        CREATE INDEX IF NOT EXISTS idx_notificaciones_cola
          ON notificaciones_email (estado, fecha_creacion);
        CREATE INDEX IF NOT EXISTS idx_notificaciones_asignacion
          ON notificaciones_email (id_asignacion);
      `);
      await client.query('COMMIT');
    } catch (error) {
      await client.query('ROLLBACK');
      throw error;
    } finally {
      client.release();
    }
  },
};
